Sp 59 home events preview section
Move-Harborfest-to-Rochester/oswego-career-dashboard pull request #11
Opened 2024-11-10 17:21 UTC by himeluddin

Changes:
- Favicon
- Changes to Event (plus missing removal functionality in the back and frontend)
- Top bar Shrinkage
- AI button removed

2024-11-12 22:27 UTC, GiessC requested changes

2024-11-12 22:27 UTC, GiessC commented on frontend/src/app/file-upload/image-upload.component.ts
> +    this._snackBar.open("Image Set to Default", 'close', {
I think this should be inside the `next` function above (line 164).

2024-11-13 15:35 UTC, himeluddin commented on frontend/src/app/file-upload/image-upload.component.ts
> +    this._snackBar.open("Image Set to Default", 'close', {
Good catch ! Thank you, fixed now

2024-11-13 17:03 UTC, GiessC approved these changes

2024-11-14 17:56 UTC, asan6602 approved these changes

2024-11-14 18:06 UTC, gregSWEN approved these changes

2024-11-14 18:07 UTC, merged