Updated links and added icons
Move-Harborfest-to-Rochester/oswego-career-dashboard pull request #3
Opened 2024-10-16 01:04 UTC by asan6602

2024-10-16 22:48 UTC, himeluddin commented
Links look great and they work great! The footer does look like it's slightly big and contents are squished to the left. Spreading it out would be an idea. Some import issues when building according to the CI, but as long it's outside the scope of this story they can be addressed later. 
![Screenshot from 2024-10-16 18-45-47](https://github.com/user-attachments/assets/fca68692-0c52-4cc3-b3ec-28b177fcb668)

2024-10-16 22:49 UTC, himeluddin approved these changes, later dismissed

2024-10-21 16:22 UTC, GiessC requested changes
Code changes look good. To make all tests pass, you need to add `HttpClientTestingModule` to the imports in `footer.component.spec.ts`. I'm not really sure how that test was affected by your changes though

2024-10-22 21:13 UTC, GiessC approved these changes

2024-10-22 21:16 UTC, himeluddin approved these changes

2024-10-23 05:49 UTC, merged